# SPDX-FileCopyrightText: (C) 2022 Avnet Embedded GmbH
# SPDX-License-Identifier: GPL-3.0-only

---
name: Mirror
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: get upstream repo
        id: upstream-repo
        run: |
          echo "upstream=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT
      - name: git-sync
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://git.yoctoproject.org/${{ steps.upstream-repo.outputs.upstream }}"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          github_token: ${{ secrets.DISPATCH_PAT }}
